version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}  # Use the DATABASE_PASSWORD environment variable
      MYSQL_DATABASE: ${DATABASE_NAME}  # Use the DATABASE_NAME environment variable
    volumes:
      - ${MARIADB_VOLUME_PATH}:/var/lib/mysql  # Use the MARIADB_VOLUME_PATH environment variable
    ports:
      - "3306:3306"  # Map container port 3306 to host port 3306

  postgresql:
    image: postgres:latest
    environment:
      #POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ${POSTGRESQL_VOLUME_PATH}:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  h2:
#    image: oscarfonts/h2
#    volumes:
#      - ${H2_VOLUME_PATH}:/h2-data  # Use the H2_VOLUME_PATH environment variable
#    ports:
#      - "9092:9092"
#    environment:
#      H2_OPTIONS: -ifNotExists -web -webAllowOthers -tcp -tcpAllowOthers

