spring:
  application:
    name: runtracer-backend-test

    logging:
    level:
      web: INFO

  server:
    port: ${SERVER_PORT}}

  flyway:
    locations: classpath:db/migration
    enabled: true
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    #username: ${DATABASE_USERNAME}
    username: postgres
    password: ${DATABASE_PASSWORD}

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/${DATABASE_NAME}
    #username: ${DATABASE_USERNAME}
    username: postgres
    password: ${DATABASE_PASSWORD}
